version: '3.1'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demonstration_shop
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222" # Порт для подключения к серверу NATS Streaming
    environment:
      - STAN_CLUSTER_ID=testShop_cluster
    command: ["--cluster_id=testShop_cluster"]

volumes:
  db:
