port: "8000"

db:
  username: "admin"
  host: "localhost"
  port: "5432"
  password: "admin"
  dbname: "demonstration_shop"
  sslmode: "disable"

nats:
  clusterId: "testShop_cluster"
  clientIdProducer: "example-publisher"
  subject: "new-subject"
  clientIdConsumer: "example-subscriber"
  channel: "shop-channel"
  URL: "nats://localhost:4222"
  durableName: "new-durable"


